name: Build Mihomo ipk

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 12 * * *'

permissions:
  actions: write
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64_generic, x86_64]

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v5

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential bzip2 clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget jq xz-utils zstd

      - name: Generate build keys
        run: |
          sudo apt-get update
          sudo apt-get install -y signify-openbsd
          signify-openbsd -G -n -c 'DO NOT USE - OpenWrt packages feed CI' -p packages_ci.pub -s packages_ci.sec
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "KEY_BUILD<<$EOF" >> $GITHUB_ENV
          cat packages_ci.sec >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Setup latest golang release
        run: |
          go version       
      
      - name: Build
        run: |
          case "${{ matrix.arch }}" in
            aarch64_generic)
              TARGET_URL="https://downloads.openwrt.org/releases/23.05.5/targets/rockchip/armv8/"
              ;;
            x86_64)
              TARGET_URL="https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/"
              ;;
          esac

          SDK=$(curl -s -L "${TARGET_URL}sha256sums" | grep sdk | sed 's/.* \*//')
          wget "${TARGET_URL}${SDK}" -O sdk.tar.xz

          mkdir sdk
          tar -xvf  sdk.tar.xz --strip-components=1 -C sdk
          cd sdk
          ./scripts/feeds update -a
          wget "${TARGET_URL}config.buildinfo" -O .config
          make defconfig
          cp -a ../net package/
          sed -i 's/PKG_VERSION:=stable/PKG_VERSION:=${{ env.TAG }}/g' package/net/mihomo/Makefile
          cat package/net/mihomo/Makefile
          make package/net/mihomo/{download,check} FIXUP=1 V=s
          cat package/net/mihomo/Makefile
          make package/net/mihomo/compile V=s

          FN=$(find bin/packages -name '*.ipk' | xargs basename)
          echo "PKG_NAME=$FN" >> $GITHUB_ENV
          cd -

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PKG_NAME }}
          path: |
            sdk/bin/packages/*/*/mihomo*.ipk

      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat README.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT
          tag=$(date +"%Y%m%d")
          echo "RELEASE_TAG=$tag" >> $GITHUB_OUTPUT

      - name: Publishing to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          file: sdk/bin/packages/*/*/mihomo*.ipk
          tag: ${{ steps.read_release.outputs.RELEASE_TAG }}
          file_glob: true
          overwrite: true
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
