name: mihomo version check
on:
  workflow_dispatch:
  #schedule:
  #- cron: 0 16 * * 5
  push:
    branches:
      - master

jobs:
  check:
    name: Check new mihomo version
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pull-requests: write  # To create a PR from that branch
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: EkkoG/openwrt-packages-version-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.REPO_TOKEN }}
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
          REPO: metacubex/mihomo
          BRANCH: master
          MAKEFILE: net/mihomo/Makefile
          CREATE_PR: true
          SOURCE_URL: https://github.com/metacubex/mihomo/archive/refs/tags/v{{version}}.tar.gz
